name: AMD64-Only Integration Tests

on:
  push: {}

jobs:
  tests:
    runs-on: ${{ matrix.runner.os }}  
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        runner:
          - os: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v6
      - name: Install TIRA Client
        run: |
          pip3 install 'git+https://github.com/tira-io/tira.git@main#subdirectory=python-client'

      - name: Test lsp
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/lsp/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test ioqp
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/ioqp/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run
