name: Integration Tests

on:
  push: {}

jobs:
  tests:
    runs-on: ${{ matrix.runner.os }}  
    timeout-minutes: 30
    strategy:
      fail-fast: true
      matrix:
        runner:
          - os: ubuntu-latest
          - os: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Dependencies
        uses: actions/setup-python@v4
      - name: Install TIRA Client
        run: |
          pip3 install 'git+https://github.com/tira-io/tira.git@rag4reports#subdirectory=python-client'

      - name: Test pyterrier-splade
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/pyterrier-splade/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test numpy-exhaustive
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/numpy-exhaustive/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test naive-search
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/naive-search/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test seismic
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/seismic/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test duckdb
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/duckdb/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      # - name: Test pyserini-lsr
      #   run: |
      #     tira-cli code-submission \
      #         --path step-03-retrieval-approaches/pyserini-lsr/ \
      #         --task lsr-benchmark \
      #         --dataset tiny-example-20251002_0-training \
      #         --command '/index-and-retrieve.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
      #         --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
      #         --platform host \
      #         --dry-run

      - name: Test pyterrier-splade-pisa
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/pyterrier-splade-pisa/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/run-pyterrier-splade.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run

      - name: Test kannolo
        run: |
          tira-cli code-submission \
              --path step-03-retrieval-approaches/kannolo/ \
              --task lsr-benchmark \
              --dataset tiny-example-20251002_0-training \
              --command '/build-and-search-kannolo-index.py --dataset $inputDataset --embedding $embeddings --output $outputDir' \
              --mount-directory '$embeddings=lsr-benchmark/lightning-ir/naver-splade-v3-doc' \
              --platform host \
              --dry-run



